# Airbnb New User Bookings

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from xgboost.sklearn import XGBClassifier

## Read in file

In [2]:
train = pd.read_csv("/Users/ziyu/Desktop/proj3_data/train_users.csv")
train.head()

id date_account_created  timestamp_first_active date_first_booking  \
0  gxn3p5htnn           2010-06-28          20090319043255                NaN   
1  820tgsjxq7           2011-05-25          20090523174809                NaN   
2  4ft3gnwmtx           2010-09-28          20090609231247         2010-08-02   
3  bjjt8pjhuk           2011-12-05          20091031060129         2012-09-08   
4  87mebub9p4           2010-09-14          20091208061105         2010-02-18   

      gender   age signup_method  signup_flow language affiliate_channel  \
0  -unknown-   NaN      facebook            0       en            direct   
1       MALE  38.0      facebook            0       en               seo   
2     FEMALE  56.0         basic            3       en            direct   
3     FEMALE  42.0      facebook            0       en            direct   
4  -unknown-  41.0         basic            0       en            direct   

  affiliate_provider first_affiliate_tracked signup_app first_device_type  \
0             direct               untracked        Web       Mac Desktop   
1             google               untracked        Web       Mac Desktop   
2             direct               untracked        Web   Windows Desktop   
3             direct               untracked        Web       Mac Desktop   
4             direct               untracked        Web       Mac Desktop   

  first_browser country_destination  
0        Chrome                 NDF  
1        Chrome                 NDF  
2            IE                  US  
3       Firefox               other  
4        Chrome                  US

In [3]:
test = pd.read_csv("/Users/ziyu/Desktop/proj3_data/test_users.csv")
test.head()

id date_account_created  timestamp_first_active  \
0  5uwns89zht           2014-07-01          20140701000006   
1  jtl0dijy2j           2014-07-01          20140701000051   
2  xx0ulgorjt           2014-07-01          20140701000148   
3  6c6puo6ix0           2014-07-01          20140701000215   
4  czqhjk3yfe           2014-07-01          20140701000305   

   date_first_booking     gender   age signup_method  signup_flow language  \
0                 NaN     FEMALE  35.0      facebook            0       en   
1                 NaN  -unknown-   NaN         basic            0       en   
2                 NaN  -unknown-   NaN         basic            0       en   
3                 NaN  -unknown-   NaN         basic            0       en   
4                 NaN  -unknown-   NaN         basic            0       en   

  affiliate_channel affiliate_provider first_affiliate_tracked signup_app  \
0            direct             direct               untracked      Moweb   
1            direct             direct               untracked      Moweb   
2            direct             direct                  linked        Web   
3            direct             direct                  linked        Web   
4            direct             direct               untracked        Web   

  first_device_type  first_browser  
0            iPhone  Mobile Safari  
1            iPhone  Mobile Safari  
2   Windows Desktop         Chrome  
3   Windows Desktop             IE  
4       Mac Desktop         Safari

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 213451 entries, 0 to 213450
Data columns (total 16 columns):
 #   Column                   Non-Null Count   Dtype  
---  ------                   --------------   -----  
 0   id                       213451 non-null  object 
 1   date_account_created     213451 non-null  object 
 2   timestamp_first_active   213451 non-null  int64  
 3   date_first_booking       88908 non-null   object 
 4   gender                   213451 non-null  object 
 5   age                      125461 non-null  float64
 6   signup_method            213451 non-null  object 
 7   signup_flow              213451 non-null  int64  
 8   language                 213451 non-null  object 
 9   affiliate_channel        213451 non-null  object 
 10  affiliate_provider       213451 non-null  object 
 11  first_affiliate_tracked  207386 non-null  object 
 12  signup_app               213451 non-null  object 
 13  first_device_type        213451 non-null  object 
 14  firs

In [5]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62096 entries, 0 to 62095
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       62096 non-null  object 
 1   date_account_created     62096 non-null  object 
 2   timestamp_first_active   62096 non-null  int64  
 3   date_first_booking       0 non-null      float64
 4   gender                   62096 non-null  object 
 5   age                      33220 non-null  float64
 6   signup_method            62096 non-null  object 
 7   signup_flow              62096 non-null  int64  
 8   language                 62096 non-null  object 
 9   affiliate_channel        62096 non-null  object 
 10  affiliate_provider       62096 non-null  object 
 11  first_affiliate_tracked  62076 non-null  object 
 12  signup_app               62096 non-null  object 
 13  first_device_type        62096 non-null  object 
 14  first_browser         

## Concat files

In [6]:
# store the country_destination
labels = train['country_destination'].values
train = train.drop(['country_destination'], axis=1)

# store the test id
test_id = test['id']

# caculate the row number 
train_row = train.shape[0]

# concat file
df = pd.concat((train, test), axis=0, ignore_index=True)

# removing id and date_first_booking
df = df.drop(['id', 'date_first_booking', 'signup_app'], axis=1)

# filling nan
df = df.fillna(-1)


## Data Preprocssing

In [7]:
print(train_row)

213451


### Date Account Create

In [78]:
df['date_account_created'] = pd.to_datetime(df['date_account_created'], format='%Y-%m-%d')

df['dac_year'] = pd.DatetimeIndex(df['date_account_created']).year
df['dac_month'] = pd.DatetimeIndex(df['date_account_created']).month
df['dac_day'] = pd.DatetimeIndex(df['date_account_created']).day

df = df.drop(['date_account_created'], axis = 1)

df.head()

timestamp_first_active     gender   age signup_method  signup_flow  \
0          20090319043255  -unknown-   NaN      facebook            0   
1          20090523174809       MALE  38.0      facebook            0   
2          20090609231247     FEMALE  56.0         basic            3   
3          20091031060129     FEMALE  42.0      facebook            0   
4          20091208061105  -unknown-  41.0         basic            0   

  language affiliate_channel affiliate_provider first_affiliate_tracked  \
0       en            direct             direct               untracked   
1       en               seo             google               untracked   
2       en            direct             direct               untracked   
3       en            direct             direct               untracked   
4       en            direct             direct               untracked   

  first_device_type first_browser  dac_year  dac_month  dac_day  
0       Mac Desktop        Chrome      2010          6       28  
1       Mac Desktop        Chrome      2011          5       25  
2   Windows Desktop            IE      2010          9       28  
3       Mac Desktop       Firefox      2011         12        5  
4       Mac Desktop        Chrome      2010          9       14

### Timestamp first active

In [79]:
tfa = np.vstack(df.timestamp_first_active.astype(str).apply(lambda x: list(map(int, [x[:4],x[4:6],x[6:8],x[8:10],x[10:12],x[12:14]]))).values)

df['tfa_year'] = tfa[:,0]
df['tfa_month'] = tfa[:,1]
df['tfa_day'] = tfa[:,2]

df = df.drop(['timestamp_first_active'], axis=1)

In [80]:
df.head()

gender   age signup_method  signup_flow language affiliate_channel  \
0  -unknown-   NaN      facebook            0       en            direct   
1       MALE  38.0      facebook            0       en               seo   
2     FEMALE  56.0         basic            3       en            direct   
3     FEMALE  42.0      facebook            0       en            direct   
4  -unknown-  41.0         basic            0       en            direct   

  affiliate_provider first_affiliate_tracked first_device_type first_browser  \
0             direct               untracked       Mac Desktop        Chrome   
1             google               untracked       Mac Desktop        Chrome   
2             direct               untracked   Windows Desktop            IE   
3             direct               untracked       Mac Desktop       Firefox   
4             direct               untracked       Mac Desktop        Chrome   

   dac_year  dac_month  dac_day  tfa_year  tfa_month  tfa_day  
0      2010          6       28      2009          3       19  
1      2011          5       25      2009          5       23  
2      2010          9       28      2009          6        9  
3      2011         12        5      2009         10       31  
4      2010          9       14      2009         12        8

### Age

In [81]:
def user_age(age):
    if age < 0:
        return 'NA' 
    elif (age < 15):
        return 15 
    elif (age <= 25):
        return 25 
    elif (age <= 35):
        return 35
    elif (age <= 45):
        return 45
    elif (age <= 55):
        return 55
    elif (age <= 65):
        return 65
    elif (age <= 75):
        return 75
    elif (age <= 85):
        return 85
    else:
        return 'NA' 

df['age'] = np.array([user_age(x) for x in df.age])
df_age = pd.get_dummies(df.age, prefix = 'age')
df = pd.concat((df, df_age), axis = 1)

df.drop(['age'], axis = 1, inplace = True)

In [82]:
df.head()

gender signup_method  signup_flow language affiliate_channel  \
0  -unknown-      facebook            0       en            direct   
1       MALE      facebook            0       en               seo   
2     FEMALE         basic            3       en            direct   
3     FEMALE      facebook            0       en            direct   
4  -unknown-         basic            0       en            direct   

  affiliate_provider first_affiliate_tracked first_device_type first_browser  \
0             direct               untracked       Mac Desktop        Chrome   
1             google               untracked       Mac Desktop        Chrome   
2             direct               untracked   Windows Desktop            IE   
3             direct               untracked       Mac Desktop       Firefox   
4             direct               untracked       Mac Desktop        Chrome   

   dac_year  ...  tfa_day  age_15  age_25  age_35  age_45  age_55  age_65  \
0      2010  ...       19       0       0       0       0       0       0   
1      2011  ...       23       0       0       0       1       0       0   
2      2010  ...        9       0       0       0       0       0       1   
3      2011  ...       31       0       0       0       1       0       0   
4      2010  ...        8       0       0       0       1       0       0   

   age_75  age_85  age_NA  
0       0       0       1  
1       0       0       0  
2       0       0       0  
3       0       0       0  
4       0       0       0  

[5 rows x 24 columns]

### One Hot Encoding

In [83]:
OHE_feat = ['gender', 
            'signup_method', 
            'signup_flow', 
            'language', 
            'affiliate_channel', 
            'affiliate_provider', 
            'first_affiliate_tracked', 
            'first_device_type', 
            'first_browser']

for f in OHE_feat:
    df_work = pd.get_dummies(df[f], prefix=f, dummy_na=True)
    df.drop([f], axis = 1, inplace = True)
    df = pd.concat((df, df_work), axis = 1)

## Label Encoding

In [84]:
vals = df.values
X = vals[:train_row]
le = LabelEncoder()
y = le.fit_transform(labels)   
X_test = vals[train_row:]

## XGBoost

In [85]:
xgb = XGBClassifier(max_depth=6, learning_rate=0.2, n_estimators=43,
                    objective='multi:softprob', subsample=1, colsample_bytree=0.5, seed=1)                  
xgb.fit(X, y)
y_pred = xgb.predict_proba(X_test)  

/Users/ziyu/opt/anaconda3/lib/python3.8/site-packages/xgboost/sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[20:23:09] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


In [86]:
print(y_pred)

[[0.0024515  0.00441451 0.00338389 ... 0.00218779 0.29774222 0.04797209]
 [0.00119244 0.00269876 0.00163332 ... 0.00098457 0.11157453 0.02173983]
 [0.00134759 0.00458451 0.00205283 ... 0.00125645 0.14216849 0.03622839]
 ...
 [0.00246553 0.00331321 0.00803184 ... 0.00153578 0.11764371 0.0160562 ]
 [0.00210442 0.00425927 0.00271164 ... 0.00120395 0.12471749 0.02683611]
 [0.00384724 0.01048904 0.0053651  ... 0.0019076  0.42947978 0.06253128]]


In [87]:
ids = []  #list of ids
cts = []  #list of countries
for i in range(len(id)):
    idx = id[i]
    ids += [idx] * 5
    cts += le.inverse_transform(np.argsort(y_pred[i])[::-1])[:5].tolist()

#Generate submission
sub = pd.DataFrame(np.column_stack((ids, cts)), columns=['id', 'country'])
sub.to_csv('/Users/ziyu/Desktop/submission.csv',index=False)